### ISSUE TITLE
link in second paragraph of README points to wrong place

### ISSUE THREAD

**Issue by vjcitn** [Bioconductor/S4Arrays#3]
points to deprecated packages

**Comment by hpages** [comment]
The package is not in Bioconductor yet so the link is not valid yet, but hopefully it will become valid soon ;-)

I believe that there is a mechanism in place on master.bioconductor.org that redirects invalid URLs starting with https://[master.]bioconductor.org/packages/ to the list of removed packages e.g. https://bioconductor.org/packages/foo
It's a little rough and can be confusing if you just made a typo in the package name.
